services:
  milvus:
    image: milvusdb/milvus:v2.3.9
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - TZ=UTC
    volumes:
      - milvus-data:/var/lib/milvus
volumes:
  milvus-data:
